---
- name: Install solr on OpenShift
  hosts: localhost
  connection: local
  vars_files:
    - "{{ PROJECT_ANSIBLE_INVENTORY }}/vaults/{{ VAULT_ID }}/vault"
  roles:
    - computate.computate_solr_openshift
